const json = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json", "access-control-allow-origin": "*", "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,OPTIONS" } });
const apiBase = (env) => env.MPESA_BASE_URL || "https://sandbox.safaricom.co.ke";
const timestamp = () => { const d = new Date(); const p = (n) => String(n).padStart(2, "0"); return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`; };
const b64 = (s) => btoa(unescape(encodeURIComponent(s)));
async function accessToken(env) { const raw = `${env.MPESA_CONSUMER_KEY}:${env.MPESA_CONSUMER_SECRET}`; const r = await fetch(`${apiBase(env)}/oauth/v1/generate?grant_type=client_credentials`, { headers: { Authorization: `Basic ${b64(raw)}` } }); const data = await r.json(); if (!r.ok || !data.access_token) throw new Error(data.errorMessage || "Unable to authenticate with M-Pesa"); return data.access_token; }
function normalizePhone(phone) { const digits = String(phone || "").replace(/\D/g, ""); if (/^07\d{8}$/.test(digits)) return `254${digits.slice(1)}`; if (/^01\d{8}$/.test(digits)) return `254${digits.slice(1)}`; if (/^254\d{9}$/.test(digits)) return digits; return null; }
async function stkPush(env, phone) { const token = await accessToken(env); const ts = timestamp(); const password = b64(`${env.MPESA_SHORTCODE}${env.MPESA_PASSKEY}${ts}`); const body = { BusinessShortCode: env.MPESA_SHORTCODE, Password: password, Timestamp: ts, TransactionType: env.MPESA_TRANSACTION_TYPE || "CustomerPayBillOnline", Amount: 10, PartyA: phone, PartyB: env.MPESA_SHORTCODE, PhoneNumber: phone, CallBackURL: env.MPESA_CALLBACK_URL, AccountReference: "BINJO-ALARM", TransactionDesc: "BINJO KSh 10 Alarm Stop" }; const r = await fetch(`${apiBase(env)}/mpesa/stkpush/v1/processrequest`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok || data.ResponseCode !== "0") throw new Error(data.errorMessage || data.ResponseDescription || "STK Push failed"); return data; }
async function stkQuery(env, checkoutRequestId) { const token = await accessToken(env); const ts = timestamp(); const password = b64(`${env.MPESA_SHORTCODE}${env.MPESA_PASSKEY}${ts}`); const r = await fetch(`${apiBase(env)}/mpesa/stkpushquery/v1/query`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify({ BusinessShortCode: env.MPESA_SHORTCODE, Password: password, Timestamp: ts, CheckoutRequestID: checkoutRequestId }) }); const data = await r.json(); if (!r.ok) throw new Error(data.errorMessage || data.ResponseDescription || "Payment query failed"); return data; }
export default { async fetch(request, env) { if (request.method === "OPTIONS") return new Response(null, { headers: { "access-control-allow-origin": "*", "access-control-allow-headers": "content-type", "access-control-allow-methods": "GET,POST,OPTIONS" } }); const url = new URL(request.url); try { if (url.pathname === "/health") return json({ ok: true, service: "binjo-mpesa", amount: 10, till: env.MPESA_SHORTCODE || "configured-server-side" }); if (url.pathname === "/api/payment/stk" && request.method === "POST") { const { phone } = await request.json(); const normalized = normalizePhone(phone); if (!normalized) return json({ ok: false, error: "Enter a valid Kenyan M-Pesa number." }, 400); const result = await stkPush(env, normalized); return json({ ok: true, checkoutRequestId: result.CheckoutRequestID, customerMessage: result.CustomerMessage || "Check your phone and enter your M-Pesa PIN." }); } if (url.pathname === "/api/payment/status" && request.method === "GET") { const id = url.searchParams.get("checkoutRequestId"); if (!id) return json({ ok: false, error: "Missing checkoutRequestId" }, 400); const result = await stkQuery(env, id); const code = String(result.ResultCode ?? ""); return json({ ok: true, paid: code === "0", pending: code === "1037" || code === "1", resultCode: result.ResultCode, resultDescription: result.ResultDesc }); } if ((url.pathname === "/api/payment/callback" || url.pathname === "/callback") && request.method === "POST") { await request.text(); return json({ ResultCode: 0, ResultDesc: "Accepted" }); } return json({ ok: false, error: "Not found" }, 404); } catch (error) { return json({ ok: false, error: error.message || "Payment service error" }, 500); } } };
